"""
Program Title : IT Automation Incident Ticket Manager
Course        : ITEC 204 - Data Structures and Algorithms
Activity      : Laboratory Activity 1

Description:
    This program simulates how a support team manages incident tickets
    generated by automation bots. It uses a LIST (a linear data structure)
    to store each ticket as a dictionary with the keys:
        - incident_id
        - bot
        - description

Operations implemented:
    1. Add a new incident ticket
    2. Display all active incident tickets
    3. Search for a ticket using its Incident ID
    4. Remove a resolved ticket
    5. Display the total number of active tickets
"""

# The list below is our linear data structure that holds all active tickets.
tickets = []


def add_ticket():
    """Add a new incident ticket to the list."""
    incident_id = input("Enter Incident ID: ").strip()
    bot = input("Enter Bot name: ").strip()
    description = input("Enter Short Description: ").strip()

    # Prevent duplicate Incident IDs
    for ticket in tickets:
        if ticket["incident_id"] == incident_id:
            print(f"\n[ERROR] Incident ID '{incident_id}' already exists.\n")
            return

    ticket = {
        "incident_id": incident_id,
        "bot": bot,
        "description": description
    }
    tickets.append(ticket)
    print(f"\n[SUCCESS] Ticket '{incident_id}' added.\n")


def display_tickets():
    """Display all active incident tickets."""
    print("\n===== ACTIVE INCIDENT TICKETS =====")
    if len(tickets) == 0:
        print("No active tickets found.")
    else:
        print(f"{'Incident ID':<15}{'Bot':<20}{'Short Description'}")
        print("-" * 70)
        for ticket in tickets:
            print(f"{ticket['incident_id']:<15}{ticket['bot']:<20}{ticket['description']}")
    print("====================================\n")


def search_ticket():
    """Search for a specific ticket using its Incident ID."""
    incident_id = input("Enter Incident ID to search: ").strip()

    for ticket in tickets:
        if ticket["incident_id"] == incident_id:
            print("\n[FOUND] Ticket details:")
            print(f"  Incident ID : {ticket['incident_id']}")
            print(f"  Bot         : {ticket['bot']}")
            print(f"  Description : {ticket['description']}\n")
            return

    print(f"\n[NOT FOUND] No ticket with Incident ID '{incident_id}'.\n")


def remove_ticket():
    """Remove a resolved incident ticket using its Incident ID."""
    incident_id = input("Enter Incident ID to remove: ").strip()

    for ticket in tickets:
        if ticket["incident_id"] == incident_id:
            tickets.remove(ticket)
            print(f"\n[SUCCESS] Ticket '{incident_id}' removed (resolved).\n")
            return

    print(f"\n[ERROR] No ticket with Incident ID '{incident_id}' found.\n")


def count_tickets():
    """Display the total number of active incident tickets."""
    print(f"\nTotal active incident tickets: {len(tickets)}\n")


def load_sample_data():
    """Preload the 10 sample incident tickets given in the activity."""
    sample_data = [
        ("INC1392939", "BOT-Inventory", "Failed to generate the daily report"),
        ("INC1392940", "BOT-Email", "Failed to send the scheduled notification"),
        ("INC1392941", "BOT-DataSync", "Encountered an error during data transfer"),
        ("INC1392942", "BOT-Invoice", "Failed to process an invoice"),
        ("INC1392943", "BOT-Report", "Failed to generate the weekly report"),
        ("INC1392944", "BOT-FileTransfer", "Failed to upload the required file"),
        ("INC1392945", "BOT-DataEntry", "Encountered an error while entering records"),
        ("INC1392946", "BOT-Backup", "Failed to complete the scheduled backup"),
        ("INC1392947", "BOT-Validation", "Failed to validate the submitted records"),
        ("INC1392948", "BOT-Notification", "Failed to send the system alert"),
    ]
    for incident_id, bot, description in sample_data:
        tickets.append({
            "incident_id": incident_id,
            "bot": bot,
            "description": description
        })
    print("\n[INFO] 10 sample incident tickets have been loaded.\n")


def show_menu():
    """Display the main menu."""
    print("======= IT AUTOMATION INCIDENT TICKET MANAGER =======")
    print("1. Add a new incident ticket")
    print("2. Display all active incident tickets")
    print("3. Search for a ticket by Incident ID")
    print("4. Remove a resolved ticket")
    print("5. Display total number of active tickets")
    print("6. Load 10 sample tickets (for testing)")
    print("7. Exit")
    print("======================================================")


def main():
    """Main program loop."""
    while True:
        show_menu()
        choice = input("Enter your choice (1-7): ").strip()

        if choice == "1":
            add_ticket()
        elif choice == "2":
            display_tickets()
        elif choice == "3":
            search_ticket()
        elif choice == "4":
            remove_ticket()
        elif choice == "5":
            count_tickets()
        elif choice == "6":
            load_sample_data()
        elif choice == "7":
            print("\nExiting program. Goodbye!")
            break
        else:
            print("\n[ERROR] Invalid choice. Please enter a number from 1 to 7.\n")


if __name__ == "__main__":
    main()